-- ============================================================
-- TembusKarir — Seed Data
-- ============================================================
-- Paket & soal contoh untuk OJK, BI, PLN, dan RBB BUMN di-seed
-- melalui migrasi 2026-04-15T01-00-00_seed_paket_seleksi.sql.
-- Paket simulasi PLN GAT di-seed melalui 2026-04-17T00-00-00_pln_tables.sql.
--
-- File ini sengaja dibiarkan kosong agar tidak menduplikasi data seed.
-- Tambahkan seed lokal khusus di sini bila diperlukan.
